---
- sudo: yes
  remote_user: ubuntu
  hosts: devlabs
  tasks: 
    - name: Actualizar los paquetes del servidor...
      apt: update_cache=yes
      tags: sys

    - name: Hacer un dist-upgrade
      apt: upgrade=dist
      tags: sys 

    - include: util-install.yml

    - include: etckeeper/etckeeper.yml
    
    - include: ufw.yml

    - include: ssh/ssh.yml