---
- sudo: yes
  remote_user: ubuntu
  hosts: devlabs
  tasks: 
    - name: Actualizar los paquetes del servidor...
      apt: update_cache=yes
      tags: syst

    - name: Hacer un dist-upgrade
      apt: upgrade=dist
      tags: sys 
    
    - name: Instalar ufw 
      apt: pkg=ufw state=present
      tags: firewall

    - name: Desactivar el firewall momentaneamente
      command: ufw disable
      tags: firewall

    - name: Activar puerto ssh
      command: ufw allow 6022
      tags: firewall

    - name: Activar puerto HTTP
      command: ufw allow 6080
      tags: firewall

    - name: Activar puerto HTTPS
      command: ufw allow 6443
      tags: firewall

    - name: Bloquear todo lo demas
      command: ufw default deny
      tags: firewall

    - name: Activar el firewall.
      command: echo 'y' | sudo ufw enable
      tags: firewall
    